### ISSUE TITLE
회원 가입 API 구현

### ISSUE THREAD

**Issue by choi-ys** [project-porko/porko-service#1]
## 요구사항
**아이디**
- 회원 아이디는 `영문` 혹은 `영문과 숫자 조합`만 가능하다.
- 회원 아이디는 `6자 이상 20자 이하`여야 한다.
- 회원 아이디는 `중복될 수 없다.`
  - 회원 아이디가 중복이 아닌 경우 `사용 가능한 아이디입니다` 문구를 출력한다. 
  - 회원 아이디 중복 시 `이미 사용중인 아이디입니다` 문구를 출력한다. 

**비밀번호**
- 회원 비밀번호는 `영문, 숫자, 특수문자를 모두 포함`해야 한다.
- 회원 비밀번호는 `8자 이상 20자 이하`여야 한다.
- 회원 비밀번호는 `암호화` 되어야 한다.

**이름**
- 회원 이름은 `10자를 초과할 수 없다.`

**이메일**
- 회원 이메일은 `40자를 초과할 수 없다.`

**본인 인증**
- 회원 가입 시 `본인 명의의 휴대폰 번호`로 `본인 인증`을 진행해야 한다.
  - 인증 번호 불일치 시 `인증번호가 일치하지 않습니다` 문구를 출력한다.

**주소** 
- 회원 주소는 `도로명/법정명 주소`와 `상세 주소`로 이루어진다.
- 상세 주소는 `30자를 초과할 수 없다.`

**성별**
- 회원은 남성, 여성 중 하나의 값을 필수로 가진다.

**이용 약관**
- 회원은 '프로모션 알림 수신 동의' 여부를 선택할 수 있다.

---
## TODO
- [ ] 회원 테이블 명세서 도식 -> DDL로 추출
- [ ] 회원 도메인(Entity) 정의
- [ ] 회원 ID 중복 검사 API 구현 및 예외 처리
- [ ] 회원 Email 중복 검사 API 구현 및 예외 처리
- [ ] 본인 인증 서비스 구현 : VerificationService interface
  - [ ] 개발 : RandomNumberGenerator
  - [ ] 운영 : [Naver SMS API와 redis를 이용한 휴대폰 본인 인증 처리](https://velog.io/@kyungwoon/%ED%9C%B4%EB%8C%80%ED%8F%B0-%EB%B2%88%ED%98%B8%EB%A1%9C-%EC%9D%B8%EC%A6%9D%ED%95%98%EA%B8%B0)
- [ ] spring-security의 PasswordEncoder를 이용한 비밀번호 암호화
- [ ] spring-validation의 JSR 380 Annotations을 이용한 입력값 유효성 검사 적용
- [ ] TC 작성 (Controller, Service)
  - [ ] Service
    - [ ] 회원 아이디 중복 검사
    - [ ] 회원 이메일 중복 검사
    - [ ] 회원 생성 TC
  - [ ] Controller
    - [ ] 회원 아이디 중복 검사
    - [ ] 회원 이메일 중복 검사
    - [ ] 회원 가입
    - [ ] 유효하지 못한 회원 가입 요청
