### ISSUE TITLE
이모지

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#119]
# 개요
반응 관련 API를 구현하기 위해 필요한 이모지 관리 테이블을 설계하고, 제공된 이모지를 저장한다.

# TODO
- [ ] 이모지 도메인 및 테이블을 설계한다.
  -  이모지 ID, 이모지, 설명,  카테고리(group)
- [ ] Local profile에서 제공된 csv를 Entity로 변환하여 데이터베이스에 저장 후 Insert Query로 추출한다.
- [ ] 테스트 편의성을 위해 data.sql에 추출한 insert query를 data.sql에 저장한다.
- [ ] 반응 목록 조회 API를 구현한다. (Slice)

# 참고 URL
- [npm unicode - emoji](https://www.npmjs.com/package/unicode-emoji)
- [github.com/Julien-Marcou/Unicode-Emoji csv repo](https://github.com/Julien-Marcou/Unicode-Emoji/blob/main/unicode-emoji.csv)
