### ISSUE TITLE
신규 회원의 위젯 생성 Event 처리

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#121]
# 개요
신규 회원의 메인 화면에 출력할 위젯을 생성하기 위해 회원 가입 이후, 위젯 생성 Event를 발행하고 기본 순서가 지정된 6개의 위젯과 순서가 지정되지 않은 2개의 위젯을 저장하는 EventListener를 구현한다.

## TODO
- [x] 신규 회원의 위젯 초기화를 위해 각 WIdgetCode에 initialSequence 필드 추가 및 기본 값 부여
- [x] 위젯 목록 캐시를 이용한 Widgets 일급 컬렉션 객체 생성
- [x] MemberWidgets 일급 컬렉션에 신규 회원의 초기화된 회원 위젯 목록 생성 부 구현
  - [x] 신규 회원의 초기화된 위젯 목록을 생성 TC 작성
- [x] 회원 가입 트랜잭션 완료 시 신규 회원의 초기화된 위젯 생성을 처리하는 EventListener 구현
   - [x] 위젯 생성 Event 객체 설계
   - [x] 회원 가입 시 위젯 생성 Event 발행
   - [x] Transaction 기점으로 Event를 발행/등록 하는 Event Publicher AOP 구현
   - [x] 회원 가입 완료 시(onCommit) EventListener 호출 여부 TC 작성
- [ ] 명확하지 않은 객체명 수정
  - [ ]  WidgetResponse -> WidgetsDto

## 고민사항
MemberWidghet은 매번 deleteAll -> saveALl 되는데 Id가 필요한지?, UK로 처리할 순 없는지 고민 필요
