### ISSUE TITLE
회원 가입 시 입/출금 내역 저장 Event 처리

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#136]
# 개요
회원 가입 시 특정 회원에 해당 하는 금융 데이터가 저장된 테이블로부터 Porko 서비스 제공을 위해 적절한 데이터 형태로 가공 후 저장하는 Event를 발행하고 처리한다.

# TODO
- [x] 회원 가입 완료 시 금융 거래 기록을 porko-service의 History로 변경하기 위한 Event 객체 정의
- [x] 회원 가입 완료 시 TransactionRecord로 부터 History로 변경 후 저장 하는 EventListener 구현
   - [x] 금융 거래 기록의 소분류 정보를 HistoryCategory의 name에 매칭
- [x] 회원 가입 완료 시 History 내역 저장 Event 발행
