### ISSUE TITLE
local 환경의 application properties 수정

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#27]
## TODO
- [x] 모든 환경 변수 설정을 porko-common으로 이관
  - [x] porko-common을 의존하는 모든 모듈은 porko-common에서 정의한 profiles별 group을 이용하여 환경 변수 주입
- [x] jwt, port 등 local application 구동에 필요한 환경 변수 추가 작성
- [x] 디버깅을 위한 로깅 관련 환경 변수 추가(p6spy, logging-level)
