### ISSUE TITLE
회원 가입 API 수정

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#33]
## 목표
기획서 변경에 따른 회원 가입 로직 수정
- 회원 가입 시 아이디 항목 제외
- 전화번호를 이용한 본인 인증 제외

## TODO
- [x] 회원 가입시 Id 항목 제거
  - [x] 요청 객체의 ID
  - [x] Entity 객체의 ID
  - [x] MemberId 제거로 인한 사이드 이펙트는 TC를 통해 확인
- [x] Id 항목 대신 Email 항목에 UK 적용
- [x] DDL 최신화
- [x] Id 항목 제거로 인한 로그인 처리 수정
- [x] Id 항목 제거로 인한 중복 검사 API 및 중복 검사 가능 항목 조회 API 수정
