### ISSUE TITLE
민감한 환경 변수 분리 및 주입

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#34]
# 문제점 인식
> Application 구동을 위해 필요한 환경 변수가 설정된 *.yml의 환경 변수 중 접속 정보, 혹은 key와 같이 `민감한 정보가 버전관리 되면서 외부로 노출`

# 목표
> 민감한 환경 변수를 `별도 파일로 추출`하여 `Application 구동 시 주입` 받아 실행 할 수 있도록 수정함으로써, 1차적으로 외부로부터 민감한 정보 노출을 방지

## TODO
- [x] application properties의 민감한 환경 변수 분리
  - [x] 계층형 구조로 `profiles 별 환경 변수 표현`을 위해 민감한 환경 변수를 *.yml 파일로 추출
  - [x] `spring.config.import`를 이용한 `env.yml 구성 파일 import`
  - [x] `${ENV_VARIABLE}`를 이용하여 분리된 `환경 변수 주입`
  - [x] 해당 파일이 노출 되지 않도록 `.gitignore` 등록
- [x] docker compose의 민감한 환경 변수 분리
  - [x] 민감한 환경 변수를 `*.env`파일로 추출
  - [x] `env_file`를 이용한 `*.env 구성 파일 import`
  - [x] `${ENV_VARIABLE}`를 이용하여 분리된 `환경 변수 주입`
  - [x] docker compose convert로 분리된 환경 변수의 주입 여부 확인

# 환경 변수 파일 분리의 한계
> 해당 `env 파일`은 `버전관리에서 제외`되므로, 협업 과정에서 다른 개발자가 추가한 환경 변수가 `누락`되거나 `잘못 전달`될 가능성이 있으며, `전달하는 과정에서 노출`될 가능성이 있음

> 이를 해결하기 위해 `git submodule`을 통해 `프로젝트 저장소 내부에 private repository를 구성`하여 외부로부터 접근을 막고, 누락 혹은 잘못 전달될 수 있는 문제점 해결
