### ISSUE TITLE
모든 위젯 목록 조회 API 구현

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#39]
# 개요
홈 화면 및 위젯 테이블 순서 편집 화면의 사용자 위젯을 위해 필요한 위젯 도메인을 설계하고 필요 기능을 구현한다.

# 목표
- 서비스에서 다루는 전체 위젯 목록 조회 API 구현
- ~~위젯 저장 API 구현~~(관리성 API는 사용자 서비스에서 구현하지 않음)
- ~~위젯 타입 변경 API 구현~~(관리성 API는 사용자 서비스에서 구현하지 않음)

# 요구사항
- 위젯은 위젯 번호와, 위젯 코드로 표현한다.
- 위젯 코드는 코드값과 설명, 위젯 타입으로 표현한다.
- 위젯 타입은 고정형, 기본형, 선택형으로 구분된다.
  - 고정형 위젯은 순서를 변경 할 수 없다.
  - 기본형 위젯은 초기 사용자 위젯의 기본 위젯 목록으로 초기화 된다.
  - 선택형 위젯은 사용자 위젯 순서 편집에서 추가 될 수 있다. 

# TODO 
- [x] 위젯 테이블 설계
  - [x] 위젯 아이디, 위젯 코드, 위젯 타입, 위젯 추가/수정에 대한 메타 데이터
    - [x] 위젯 타입 
      - FIXED : 고정형
      - DEFAULT : 기본형
      - OPTIONAL : 선택형
    - [x] 위젯 코드 : 코드명, 설명, 위젯 타입
      - TODAY_CONSUMPTION_WEATHER : 오늘 소비 날씨, FIXED
      - REMAINING_BUDGET : 이번달 남은 예산
      - UPCOMING_EXPENSES : 다가오는 지출
      - LAST_MONTH_EXPENSES : 저번 달에 쓴 돈
      - CURRENT_MONTH_EXPENSES : 이번달 현재 소비
      - CURRENT_MONTH_CARD_USAGE : 이번달 카드 실적
      - MY_CHALLENGE : 나의 챌린지
      - DAILY_EXPENSES : 매일 나가는 돈
      - CREDIT_SCORE : 나의 신용 점수
      - INVESTMENT_RANKING : 투자 랭킹
      - STEP_COUNT : 나의 걸음 수
      - DAILY_HOROSCOPE : 오늘의 운세
- [x] 위젯 엔티티 설계
- [x] 전체 위젯 목록 조회 API 구현
- [x] [성능 개선] 로컬 캐시를 이용한 전체 위젯 목록 조회 API 

# 위젯 종류
오늘 소비 날씨 (fixed order)
이번달 남은 예산 (default order, 1)
다가오는 지출 (default order, 2)
저번 달에 쓴 돈 (default order, 3)
이번달 현재 소비 (default order, 4)
이번달 카드 실적 (default order, 5)
나의 챌린지 (default order, 6)
매일 나가는 돈 (optional)
나의 신용 점수 (optional)
투자 랭킹 (optional)
나의 걸음 수 (optional)
오늘의 운세 (optional)
나의 챌린지 (optional)
