### ISSUE TITLE
사용자 위젯 순서 저장/변경 API

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#40]
# 개요
사용자 홈 화면의 각 위젯 순서를 저장/변경 하는 API

# 목표
사용자가 설정한 순서가 지정된 위젯 목록을 입력받아 저장한다.

# 요구사항
- 최초 위젯 순서 기본값은 아래와 같이 설정한다.
  - 1. 이번달 남은 예산
  - 2. 다가오는 지출
  - 3. 저번 달에 쓴 돈
  - 4. {이번달}월의 현재 소비
  - 5. 이번 달 카드 실적
  - 6. 나의 챌린지
- 위젯 순서를 저장 할 수 있다.
- 순서가 지정된 위젯 목록은 최소 6개, 최대 6개만 저장할 수 있다.
- 위젯 순서는 1부터 6 까지만 부여될 수 있다.
- 순서 고정 타입 위젯은 순서를 변경 할 수 없다.
- 회원은 중복된 위젯을 소유할 수 없다.

# TODO 
- [x] 위젯 순서 테이블을 설계
- [x] 위젯 순서는 1부터 순차적으로 부여
- [x] 위젯 이름은 Enum을 이용하여 상수로 표기
- [x] 회원 ID와 위젯 ID에 대한 Unique 제약 조건 추가
- [x] 위젯 순서 변경 요청을 순서가 지정된 위젯으로 변경 
- [x] 순서가 지정된 위젯 저장 시
  - [x] 기존 저장된 위젯 순서 목록이 없는 경우 순서가 지정된 위젯 목록을 요청 받아 그대로 저장
  - [x] 기존 저장된 위젯 순서 목록이 있는 경우, 위젯 기존 순서 목록을 모두 삭제하고 순서가 지정됫 위젯 목록을 그대로 저장
  - [x] 새롭게 순서가 지정된 위젯 목록을 저장하는 과정에서 예외가 발생하면 트랜잭션 처리하여 롤백하고, 저장 실패 이벤트 발행 및 로그 저장
- [x] 유효성 검증
  - [x] 변경 대상 위젯의 개수가 6개가 아닌 경우
  - [x] 변경 대상 위젯에 중복이 포함된 경우
  - [x] 변경 대상 위젯의 순서가 중복된 경우
  - [x] 변경 대상 위젯에 고정 타입 위젯이 포함된 경우
  - [x] 변경 대상 위젯의 순서가 1~6범위가 아닌 경우
  - [x] 변경 대상 위젯에 존재 하지 않는 위젯이 포함된 경우

## 구현 시 주의 사항
- 각 위젯 저장 시 다른 컬럼 값으로 정렬하는 것이 아닌 사용자가 지정한 순서 그대로 저장한다.

# 참고 
## [위젯 종류](https://github.com/orgs/project-porko/projects/3/views/7?pane=issue&itemId=64240354)
