### ISSUE TITLE
LocalCahce 적용(Caffeine)

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#43]
# 개요
- 특별한 성능상 이슈나 개선의 여지가 없지만 정해진 기간 내 성능상 문제를 발견할 만큼의 트래픽을 확보하기 어려움
- 그럼에도 `모든 위젯 조회 API`는 별도의 호출 조건이 없는 정적 CODE 데이터로 캐시 TTL 내에서 수정/삭제 등의 변경이 일어날 가능성이 거의 없어, 
- 해당 데이터를 조회 하기 위해 매번 DB 커넥션을 맺는 부분을 개선하기 위함
- 별도의 호출 조건이 없는 API이므로 Global Cache가 아닌 Local Cache를 이용

# Local Cache 의존성 선정
## 고려 대상
- Spring Boot Local Cache : Spring 3.1 부터 지원, Heap 영역에 ConcurrentHashMap 기반 데이터 캐싱
- EhCache : 다양한 기능 제공
- Caffeine : read/write 성능 상 벤치 마크가 압도적

이에 따라 최근까지 Issue 및 PR이 활발하고, 비슷한 기능을 제공하는 제품군 중 read/write 성능이 압도적이며, 현재 어플리케이션에서 비교적 복잡한 캐싱 기법이 필요하지 않으므로 Caffeine 선정

# 목표
- Caffeine Local Cache를 이용하여 모든 위젯 조회 API 호출 시 캐싱된 데이터를 제공하여 DB 커넥션을 줄이고 응답시간을 개선

# TODO
- [x] Caffeine 사용을 위한 의존성 추가
- [x] CaffeineCacheManager 설정
- [x] 모든 위젯 조회 Service Layer에 Caching 적용
- [x] Caching 적용 여부 확인을 위한 TC 작성
