### ISSUE TITLE
소비 날씨,아이템,월별 일 수 enum 구현

### ISSUE THREAD

**Issue by ratcomp9992** [project-porko/porko-service#52]
# 개요
지출 금액에 따른 소비 날씨와, 후회 아이템에 대한 데이터가 저장될 패키지 구현

# TODO 
- [ ] 소비 날씨 enum 클래스
  - [ ] 날씨 구분 메서드 구현
- [ ] 후회 아이템 enum 클래스
  - [ ] 후회 아이템 구분 메서드 구현
- [ ] 월별 일 수 enum 클래스
  - [ ] 윤년의 2월은 29일
 
- [ ] 올바르지 못한 값이 파라미터로 넘어왔을 때에 대한 예외처리
