### ISSUE TITLE
DockerFile 작성 : Dockerizing (경량화)

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#74]
# 개요
Gradle을 이용한 Spring Boot Project Build 및 Build 결과 생성된 artifact 기반의 Docker image build를 위한 Dockerfile을 작성한다.
JVM 기반의 Project Docker Build 결과 생성되는 다소 무거운 Docker Image의 경량화를 위해 Multi stage build를 수행한다.

# TODO
- [x] Docker Image 생성을 위한 Dockerfile 작성
- [x] Docker Image에 포함할 Gradle build 관련 설정 추가
- [x] Docker Image 경량화를 위한 Multi stage build layer 작성
- [x] Docker Container의 사용자가 root가 아닌 필요 권한이 부여된 별도 사용자 생성 및 적용

# 주요 작업 사항
build 및 pull&push 등 전체 적인 deploy 시간 단축을 위한 이미지 경량화
- alpine, slim 등 가벼운 base 이미지 사용
- multi-stage build
- 불필요 바이너리 파일 제거
- layered build

https://velog.io/@nowniz/Docker-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EA%B2%BD%EB%9F%89%ED%99%94
