### ISSUE TITLE
Git Submodule을 이용한 설정 파일 분리

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#76]
# 개요
Application 구동을 위해 필요한 환경 변수 중 접속 정보, secret key와 같은 민감한 정보의 외부 유출 방지 및 용이한 관리를 위해 private repo로 구성된 submodule을 구성한다.

# TODO
- [x] private repo 생성(porko-properties)
- [x] target repo(porko-service)에 private repo submodule 추가
  - git submodule add {submodule target repo url} {directory path} 
  - git submoudle status
  - ls -al .git/modules/{directory}
- [x] porko-common의 *.yml private repo로 이관
- [x] 연동된 submodule 초기화
  - git submodule init --remote 
- [x] submodule의 변경 사항을 target repo에 반영
  - git submodule update --remote
  - git submodule foreach git pull
- [x] porko-common copy task 작성 및 depends on bootJar

```
## submodule 등록
- git submodule add {submodule repo} {directory path}
- git commit -am >> submodule meta files
## submodule 연동
- git submodule init --remote
- git submodule status

## submodule 제거
- git submodule deinit -f vault
- rm -rf .git/modules/vault
- git rm -f vault
```
