### ISSUE TITLE
API Docs 제공을 위한 Swagger 적용

### ISSUE THREAD

**Issue by re-mora** [project-porko/porko-service#83]
# 개요
API docs 제공 및 Test 환경 제공을 위한 Swagger 적용

# TODO
- [x] swagger 의존성 추가
- [x] swagger 구동을 위한 설정 추가
- [x] swagger endpoint 허용을 위한 SecurityConfig 인가 정책 수정
- [x] swagger를 통한 API 호출 허용 처리를 위한 content-type matching rule 제거
